version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: kondayDB
    environment:
      POSTGRES_USER: konday
      POSTGRES_PASSWORD: konday
      POSTGRES_DB: kondaydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
