version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: bookDB
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
      POSTGRES_DB: bookdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
